[target.aarch64-linux-android]
linker = "aarch64-linux-android33-clang"
rustflags = [
    "-C", "link-arg=-lc++_shared",
    "-C", "link-arg=-z", "link-arg=max-page-size=16384"
]

[target.armv7-linux-androideabi]
linker = "armv7-linux-androideabi33-clang"
rustflags = [
    "-C", "link-arg=-z", "link-arg=max-page-size=16384",
    "-C", "link-arg=-z", "link-arg=common-page-size=16384",
    "-C", "link-arg=-lc++_static",
    "-C", "link-arg=-lc++abi_static",
    "-C", "link-arg=-Wl,--export-dynamic"
]

[target.i686-linux-android]
linker = "i686-linux-android33-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android33-clang"
